#!/usr/bin/env ruby

minutes = ARGV[0].nil? ? 25 : ARGV[0].to_i
seconds = minutes * 60
elapsed = 0

`say "focused work time begins now, for #{minutes} minutes"`
puts "[#{Time.now}] starting a #{minutes} minute pomodoro"

seconds.times do |i|
  print '.'

  if ((i + 1) % 60) == 0
    elapsed += 1
    puts; puts "[#{Time.now}] #{elapsed} minute#{elapsed > 1 ? 's' : ''} elapsed"
  end

  sleep 1
end

puts "[#{Time.now}] finished"
`say "pomodoro is done, stretch your legs"`
